/**
 * @file return_codes.h
 * @author Yuval Krinsky (ykrinksy@gmail.com)
 * @brief Return codes of the program.
 * @date 2020-09-17
 */

typedef enum return_code_e{
    RC_UNINITIAILIZED = -1,
    RC_SUCCESS = 0,
    RC_SHELL__INIT_SERVER__BAD_PARAMS,
    RC_SHELL__INIT_SERVER__SOCKET_INIT_FAILED,
    RC_SHELL__INIT_SERVER__SOCKET_BIND_FAILED,
    RC_SHELL__INIT_SOCKET__SOCKET_LISTEN_FAILED,
    RC_SHELL__HANDLE_CONNECTION__SOCKET_ACCEPT_FAILED,
    RC_SHELL__HANDLE_CONNECTION__FORK_FAILED,
    RC_SHELL__DESTROY_SERVER__BAD_PARAMS,
    RC_SHELL__DESTROY_SERVER__CLOSE_SOCKET_FAILED,
    RC_SHELL__START_SHELL__EXEC_FAILED,
    RC_SHELL__START_SHELL__DUP2_FAILED,

    RC_BACKDOOR__MAIN__FCNTL_FAILED,
} return_code_t;
